package com.SWE.Controllers;

import java.sql.SQLException;
import java.util.Collection;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.SWE.Entities.User;
import com.SWE.Repositories.UserRepository;


@RestController
public class UserController {
	// This means to get the bean called userRepository Which is auto-generated by Spring,
			//we will use it to handle the data
	@Autowired
	private UserRepository userRepository;
	
    @RequestMapping("/onlinestore/register/{name}/{username}/{email}/{password}/{type}")
    public User login(Model model, @ModelAttribute User newUser, @PathVariable String name, @PathVariable String username, 
    		@PathVariable String email, @PathVariable String password,@PathVariable String type) throws ClassNotFoundException, SQLException {
    	
    	model.addAttribute("newUser", new User());
    	System.out.println(password);
    	System.out.println(username);
    	System.out.println(email);
    	System.out.println(type);
//    	User newUser = new User();
//    	newUser.setName(name);
//    	newUser.setName(username);
//    	newUser.setName(email);
//    	newUser.setName(password);
//    	newUser.setName(type);
    	userRepository.save(newUser);
    	System.out.println(newUser.getPassword());
    	System.out.println(newUser.getEmail());
    	return newUser ;
    }
    
}